### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sharif2008** [sharif2008/logstamping#1]
- [ ] Row log with chunk N=1 node=1 no timer  - check time & storage
- [ ] Hashed log with chunk N=1 node=1 no timer - check time & storage
- [ ] Row log with chunk N=1 node=3 - check time & storage
- [ ] Hashed log with chunk N=1 node=3 - check time & storage
- [ ] Hashed log with chunk N=2 node=3 - check time & storage
- [ ] Hashed log with chunk N=5 node=3 - check time & storage
- [ ] Hashed log with chunk N=10 node=3 - check time & storage
